wandb_version: 1

epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.004813136907703695
wd:
  desc: null
  value: 0.0820499945337202
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.5
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690259251.411102
    t:
      1:
      - 1
      - 4
      - 5
      - 8
      - 28
      - 35
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 8
      - 28
      - 35
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.11
      5: 0.15.5
      8:
      - 1
      - 5
