wandb_version: 1

epochs:
  desc: null
  value: 20
layers:
  desc: null
  value: 28
learning_rate:
  desc: null
  value: 0.009183531301361089
wd:
  desc: null
  value: 0.02800835249874537
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.10
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1694110392.757365
    t:
      1:
      - 1
      - 4
      - 5
      - 28
      - 35
      - 53
      - 55
      - 105
      2:
      - 1
      - 4
      - 5
      - 28
      - 35
      - 53
      - 55
      - 105
      3:
      - 2
      - 23
      - 37
      4: 3.10.11
      5: 0.15.10
      8:
      - 1
      - 5
