wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690398900.872828
    t:
      1:
      - 1
      - 5
      - 28
      - 35
      - 53
      - 55
      2:
      - 1
      - 5
      - 28
      - 35
      - 53
      - 55
      3:
      - 23
      4: 3.10.11
      5: 0.15.7
      8:
      - 1
      - 5
