wandb_version: 1

epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.009684990300152806
wd:
  desc: null
  value: 0.09088628701382712
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.7
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690309295.332253
    t:
      1:
      - 1
      - 4
      - 5
      - 28
      - 35
      - 53
      - 55
      3:
      - 23
      4: 3.10.11
      5: 0.15.7
      8:
      - 1
      - 5
