wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.10
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1694110333.223173
    t:
      1:
      - 1
      - 4
      - 5
      - 28
      - 35
      - 53
      - 55
      - 105
      2:
      - 1
      - 4
      - 5
      - 28
      - 35
      - 53
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.10.11
      5: 0.15.10
      8:
      - 1
      - 5
