wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.5
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1689778566.110643
    t:
      1:
      - 1
      - 5
      - 8
      - 28
      - 35
      - 53
      - 55
      2:
      - 1
      - 5
      - 8
      - 28
      - 35
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.10.11
      5: 0.15.5
      8:
      - 1
      - 5
Random Forest Classifier:
  desc: null
  value:
    bootstrap: true
    ccp_alpha: 0.0
    class_weight: null
    criterion: gini
    max_depth: null
    max_features: sqrt
    max_leaf_nodes: null
    max_samples: null
    min_impurity_decrease: 0.0
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    n_estimators: 100
    n_jobs: -1
    oob_score: false
    random_state: 123
    verbose: 0
    warm_start: false
