wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.5
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1689778540.993452
    t:
      1:
      - 1
      - 5
      - 8
      - 28
      - 35
      - 53
      - 55
      2:
      - 1
      - 5
      - 8
      - 28
      - 35
      - 53
      - 55
      3:
      - 23
      4: 3.10.11
      5: 0.15.5
      8:
      - 1
      - 5
setup:
  desc: null
  value:
    Session id: 123
    Target: 90A_10B
    Target type: Binary
    Original data shape:
    - 2572
    - 101
    Transformed data shape:
    - 4793
    - 93
    Transformed train set shape:
    - 4536
    - 93
    Transformed test set shape:
    - 257
    - 93
    Ignore features: 8
    Ordinal features: 12
    Numeric features: 72
    Categorical features: 20
    Preprocess: true
    Imputation type: simple
    Numeric imputation: mean
    Categorical imputation: mode
    Maximum one-hot encoding: 1
    Encoding method: null
    Fix imbalance: true
    Fix imbalance method: SMOTETomek
    Transformation: true
    Transformation method: yeo-johnson
    Normalize: true
    Normalize method: zscore
    Fold Generator: StratifiedKFold
    Fold Number: 10
    CPU Jobs: -1
    Use GPU: false
    Log Experiment: WandbLogger
    Experiment Name: 90A_10B Multilabel Stratified KNN predict model
    USI: '8624'
